### ISSUE TITLE
Bunpro: Keyboard pops up when using this script on mobile.

### ISSUE THREAD

**Issue by Aarixx** [ezhmd/anki-mode#1]
Posting this here in case someone wanted to use this script in hopes of making it easier to use on mobile as the keyboard pops up after each submission which can get very annoying.

Adding document.getElementById("study-answer-input").disabled = true;

after the header will disable the text input and has been working in my test.

**Comment by echamudi** [comment]
Thanks for your notes.

I don't use android device so I didn't notice this problem. I'll check your snippet and update the code accordingly.
